### ISSUE TITLE
so every now and again after a server restart players cannot join, only way it reboot host machine

### ISSUE THREAD

**Issue by thebikwirm** [Elrol/ServerUtils#21]
so as the title says every now and again the server prevents people from joining comes with this error code
```[12May2024 04:56:05.902] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /157.211.74.159:55954
java.lang.NullPointerException: null
	at dev.elrol.serverutilities.events.ChunkHandler.enterChunkEvent(ChunkHandler.java:53) ~[serverutilities:1.16.5-2.8.0]
	at net.minecraftforge.eventbus.ASMEventHandler_205_ChunkHandler_enterChunkEvent_EnteringChunk.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:325) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217448_f(ServerWorld.java:801) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217435_c(ServerWorld.java:781) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:185) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]```

**Comment by thebikwirm** [comment]
[2024-05-12-3.log](https://github.com/Elrol/ServerUtils/files/15286275/2024-05-12-3.log)

on 16.5
